name: dax
description: It is a full-featured scripting language that can run dart-like code.
version: 1.0.0
homepage: https://github.com/juopian/dax

environment:
  sdk: '>=2.14.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0