import "package:flutter/material.dart";


final colorMap = {
  'red': Colors.red,
  'pink': Colors.pink,
  'deepOrange': Colors.deepOrange,
  'orange': Colors.orange,
  'amber': Colors.amber,
  'yellow': Colors.yellow,
  'lime': Colors.lime,
  'lightGreen': Colors.lightGreen,
  'green': Colors.green,
  'teal': Colors.teal,
  'cyan': Colors.cyan,
  'lightBlue': Colors.lightBlue,
  'blue': Colors.blue,
  'indigo': Colors.indigo,
  'purple': Colors.purple,
  'deepPurple': Colors.deepPurple,
  'blueGrey': Colors.blueGrey,
  'brown': Colors.brown,
  'grey': Colors.grey,
  'black': Colors.black,
  'black12': Colors.black12,
  'black26': Colors.black26,
  'black38': Colors.black38,
  'black45': Colors.black45,
  'black54': Colors.black54,
  'black87': Colors.black87,
  'white': Colors.white,
  'white10': Colors.white10,
  'white12': Colors.white12,
  'white24': Colors.white24,
  'white30': Colors.white30,
  'white38': Colors.white38,
  'white54': Colors.white54,
  'white60': Colors.white60,
  'white70': Colors.white70,
};